#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

source("_init.R")

# UI ####
ui <- fluidPage(theme = shinytheme("superhero"),
  # STYLE FUNCTIONS ####
  labelSuppress("symbol"),
  styleEdit("h4", "margin-top:0px"),
  styleEdit("#symbolsubmit", "background:#FFFFFF47"),
  #styleEdit("#infl_correction", "font-size:110%"),
  
  # TITLE ####
  title = "investment-simulator",
  br(), #black line on top
  
    sidebarLayout(
      mainPanel(align= "center", width = 5, 
                hr(),
                p(h2("investment-simulator_v1", inline=T), "first release: 2023.08.11"),
                div(align="left", style="margin-left:25%",
                  em("about this tool:", 
                      a("Readme", href="https://github.com/C0dingM0nk3y/investment-simulator/blob/main/README.md"),
                      "|", a("GitHub Repository", href="https://github.com/C0dingM0nk3y/investment-simulator")),br(),
                  em("about me:", a("C0dingM0nk3y", href="https://github.com/C0dingM0nk3y/")),
                ),
                hr(),
                ),
      sidebarPanel(align = "center", width = 7, style="margin:2% 10%;padding:2% 5%",
               #h4("What does it do?") %>% u(),
               p("This script use ",u("historical data"), "from different investments, to simulate the purchase of a ", u("fixed value"), "of the ", u("defined asset, every 30 days"), "starting from the", u("start date"), "until today(*)."),
               br(),
               p(text_col(color="orange", 
                         em("*this strategy is called DCA. Scroll to the bottom to find a description and some references")),
               ),                  
         ),
    ),

  # NAVBAR ####
  navbarPage(theme = shinytheme("superhero"),
    title = "Select one Investment Strategy:",
    
    # DCA SIMULATOR ####
    tabPanel(title=strong("DCA simulator"),
             
     #> PARAMETER SETTING ####
     ## fluidRow() layout, desined to occupy 2 rows on computer (2 x 12 width = 24)
     ## Use gray backgroun for input, and black for results. 
     fluidRow(
       
       #>> LEFT SECTION - Instructions ####
       column(width = 3, align="center",
          h4("How to use this tool?") %>% u(),
          p(align="left", style="margin-left:10px",
            sstrong("1. Choose one asset"), br(),
            sstrong("2. Set Amount to invest")," and", sstrong("inflation correction"), br(),
            sstrong("3. Select a Date in the past"),".",br(),
            
          ),
          p("all paramenters can be ", text_col("changed dynamically", col="#619CFF"),
            "to test their influence on the final outcome."),
          br(),
          p(em("How much would you have earned if you did so?")),
          p(em("Was there a best time to begin investing?")),
          
          hr(),
          div( # separate box
            
            #div(style="background:white; color:black; font-size:75%; width:70%",
            div(align="left", style="font-size:75%; width:100%; color:#000000; background-color: #FFFFFFb0; padding:20px",
                h4(u("Common investments Symbols:"), align="center", style="margin-top:0px"),
                p(style = "margin-left:10px", em(
                  strong("^GSPC"), "=  S&P500 (Index)",br(),
                  strong("^IXIC"), "=  NASDAQ (Index)",br(),
                  strong("^DJI"), "=  Dow Jones Industrial Average (Index)",br(),
                  strong("^TNX"), "=  Treasury Yield 10 years (Index)",br(),
                  strong("^ERIX"), "=  European Revewable Energy Total (Index)",br(),
                  br(),
                  strong("SPY"), "=  S&P500 Index Tracker (ETF)",br(),
                  strong("VTI"), "=  Vangard Total Stock (ETF)",br(),
                  strong("EEM"), "=  Emerging Markets (ETF)",br(),
                  strong("EWI"), "=  Italian Market (ETF)",br(),
                  br(),
                  strong("GOOG"), "=  Google (Stock)",br(),
                  strong("AAPL"), "=  Apple (Stock)",br(),
                  br(),
                  strong("BTC-USD"), "=  Bitcoin (Crypto)",br(),
                  strong("ETH-USD"), "=  Ethereum (Crypto)",br(),
                )),
            ),
          ),
       ),

       #>> INPUT: middle section ####
      column(width=6, align="center",
          fluidRow(
             column(7, align="center", style="padding-left:0px;padding-right:0px",
               sidebarPanel(width=12, # INPUT BOX
                  h4("1. Chose on Asset from", style="padding-top:0px",
                     a("Yahoo Finance", href="https://finance.yahoo.com/lookup/?guccounter=1"),),
                  
                  h5(align="left", 
                    "a. Browse Yahoo Finance Search Engine",
                    a("(link)", href="https://finance.yahoo.com/lookup/?guccounter=1"),
                    "to find the correct", text_col("Symbol spelling"), "for the desired investment.", ),
                  h5(align="left", 
                     "b. Paste it below and hit", code_col('Search')),
                  
                  # split columns in 2 parts (to align search box to search button)
                  fluidRow(
                    column(7, 
                           textInput("symbol", label="", value = "SPY",  width = "100%",
                                                  placeholder = "Symbol Name"),),
                    column(5, align="left",
                           actionButton("symbolsubmit", label = "Search", width = "100%"),
                    ),
                  ),
                  p(style="font-size:90%", em("Note: some symbol names may include special char.",br(),
                  "(e.g. include ",code_col("^", text_col = "black"), "for", code_col("^GSPC", text_col = "black")),")"),
                  ),
             ),
             column(5, style="padding-left:0px;padding-right:0px",
                sidebarPanel(width=12, # INPUT BOX
                             h4("2a. Investment Amount"),
                             # split columns in 2 parts (to align search box to search button)
                             fluidRow(style="margin-bottom:-20px",
                               column(2, style="padding:0px",
                                      align="right", h5("Buy")),
                               column(5, numericInput("monthly_inv", width="100%", label=NULL,
                                          value = 100, min = 0, step = 100)),
                               column(5, style="padding:0px",
                                      align="left", h5("$ every month")),
                             ),
                             
                             hr(),
                             h4("2b. Correct for inflation"),
                             div(style="width:90%;font-size:80%;margin:0px",
                                 em("Purchasing power of $ was higher in the past then it is now.",)),
                             checkboxInput("infl_correction", value = FALSE,
                                           label = span(style="color:orange;font-size:125%",
                                                        "Tick to correct for inflation.")),
                ),
             ),
          column(12, style="padding-left:0px;padding-right:0px",
             sidebarPanel(width=12, # INPUT BOX
                          style="padding:0px 10%",
                          h4("3. Select investment Start Date", style="padding-top:15px"),
                          plotOutput("market", height = "200px"),
                          div(style="padding-left:9%;padding-right:7%",
                            uiOutput("ui_startDate"),
                            ),
                          p("Investment duration:", strong(style="color:orange", textOutput("duration", inline = T))),
             ),
             ),
          ),
          ),
          #>> RIGHT SECTION - Simulation ####
          column(width=3, align="center", style="background:#FFFFFF;color:black",
                    
                 h3("Simulation Results"),
                 fluidRow(style="margin-bottom:-20px",
                   column(3, align="center", style="padding-right:0",
                    h4(strong("Selected Strategy:")),
                   ),
                   column(9, style="padding-right:25px",
                    htmlOutput("strategy"),
                   ),
                   ),
                  hr(),
                 fluidRow(align="center",style="margin-top:-20px;margin-bottom:-20px",
                   column(6,
                          div(style="background:#f7972055;margin:5px 6%;padding:5px 0px",
                              h5(strong("Simulated Data"),style="padding-top:15px"),
                              tableOutput("endopoints"),
                              ),
                   ),
                   column(6,style="padding-top:3%;padding-right:8%",
                          h5(strong("Average Yearly Returns:"), style="margin-top:5px",),
                          div(style="color:black;background:#619CFF;width:95%;padding:15px",
                            strong(textOutput("apy", inline = T),"%"),
                            ),
                          h5(strong("Total Returns: ")),
                          div(style="color:black;background:#619CFF;width:95%;padding:5px",
                            strong(textOutput("yield", inline = T),"$"),br(),
                            strong(style="color:white","(", textOutput("roi", inline = T),"%)"),
                          ),
                   ),
                   ),
                  hr(),
                  plotOutput("end_plot", height = "325px", width = "100%"),
                 ),
 ),

  hr(),
  div(align="center", 
      h1("Investment breakdown"),
      h4(style="color:orange", em("WIP: UI and texts are still under development."),),),
  
  #fluidRow(align="center",
  #  column(4,
  #         h4("Comparison: invested vs. value"),
  #         plotOutput("hist", height = "300px"),
  #         ),
  #  column(4, style = 'border-left: 1px solid',
  #         h4("Profit and Losses (PNL)"),
  #         plotOutput("pnl", height = "300px"),
  #         ),
  #  column(4, style = 'border-left: 1px solid',
  #         h4("Asset Accumulation (for each year)"),
  #         plotOutput("asset", height = "300px"),
  #         ),
  #),
  hr(),
  fluidRow(align="center",
           column(3,
            sidebarPanel(width=12,style="margin-top:20%",
                  h3("How much was it purchased",br(),"year by year?"),
                  p(em("add description"))
                  ),
           ),
           column(5,
                  h4("DCA: investment growth over time"),
                  plotOutput("dca_val", height = "250px"),
                  plotOutput("dca_qnt", height = "250px"),
           ),
           column(3,style="padding:20px",
                  h4(u("A few details to pay attention to")),
                  p(sstrong("Investment growth trajectory is not linear"),br(),
                    "Specifically, the ", code_col("invested value"), "increases linearly", 
                    em("(as each yar, the same amount of $ is added to the total from previous year)"),br(),
                    "However, depending on current price for the asset, the", code_col("amount of purchased asset"),
                    "changes year by year.",),
                  p(sstrong("Assets is accumulated more quicky when the price does down"),br(),
                    "Since the ", code_col("final value"), "of the investment will be based on", 
                    code_col("how much asset"), "is on hold (top panel)", em("and not on how much it was invested (bottom panel))"),
                    "it is evident that most returns come from purchases done when the prices were lower than average",),
                  div(style="background:#619CFF55;margin:0px 15px;margin-bottom:15px",
                    em("however, this is also the main reason for which most poeple do not invest:", 
                              strong("until they acquire the correct investor mindset"),"(see below)")),
                  p(sstrong("Most income comes from very old investments"),br(),
                  "When looked from the perspective of many years (>15 years), most of currently owned asset, was purchased many years before, when global prices were lower.",
                  "This is one of the main reasons for which ", text_col("starting investing as early as possible"), "is key for a successful DCA"),
           ),
  ),
  hr(),
 fluidRow(align="center",
          column(3,
                 sidebarPanel(width=12,
                    h3("Has it always been an easy ride?" ),
                    h4("aka. tackling hardest challenge for any investor: their emotions", style="color:#619CFF"),
                    br(),
                    p(em("Would you have survived the pressure to sell?")),br(),
                    p(em("Was it worth to endure the drawbacks, to enjoy the final reward?")),
                    hr(),
                    sstrong("Investing is not technically difficult, but for most people, the psychological challenge is the harderst to overcome"),
                 ),
          ),
          column(5,
                 h4("Profit and Losses: was it always a good ride?"),
                 plotOutput("psych", height = "350px"),
          ),
          column(3,align="left", style="padding:20px",
                 h4(u("Investor Psychology"), align="center"),
                 "You will experience", span_col("losses up to", bg_color ="red"),
                 div(style="font-size:150%;color:red;margin-left:15px",
                     textOutput("loss_minValue", inline = T), "/", textOutput("loss_min", inline = T), "from invested value"), 
                 br(),
                 "and you investments ", span_col("will be in negative", bg_color ="red"), "for a total of",
                 div(style="font-size:150%;color:red;margin-left:15px",
                   textOutput("loss_weeks", inline = T), "weeks"), 
                 hr(),
                 "But after", 
                 div(style="font-size:150%;color:orange;margin-left:15px",
                                   textOutput("end_time", inline = T)),
                 "your investment will", span_col(" yield", bg_col="#619CFF"), ":",
                 div(style="font-size:150%;color:#619CFF;margin-left:15px",
                     textOutput("end_pnl", inline = T), "/", textOutput("end_roi", inline = T), "from invested value"), 
          ),
 ),
 hr(),
  sidebarLayout(
    sidebarPanel(style="margin:100px -70px 0px 70px; background-color:#FFFFF99",
      h3("What is Dollar Cost Averaging?"), 
    ),
    mainPanel(width=7, style="margin:50px 0; padding:5rem;padding-left:10rem;background-color:#FFFFFF45",
              p(strong("Dollar Cost Averaging (DCA) -"), 
                a(href="https://en.wikipedia.org/wiki/Dollar_cost_averaging", "link to wikipedia"),
                br(),
                "DCA refers to the practice of purchasing a ",strong("fixed value"), "of a asset at a", strong("specific interval of time"), "and", strong("regardless of current market price"), br(),
                em("For example, a simple DCA strategy may be to buy 100€ worth of an ETF tracking the S&P500 index every 30 days. This is the defoult setting for this web-tool."),
              ),
              p("DCA is one of the simpler-yet-effective LONG-TERM investment strategy. As there is ", u("no attempt to time the market"), "this strategy can be completely passive, and there is no need for the investor to costantly be updated on current market situation. By splitting the investment into many small instances, the investor is buying the asset on an average price, and minimizing the effect of market volatility. While there may be time at which the investment will seem to be in loss, keep buying at a discounted price will ensure an even higher profit on the subsequent expansion phase f the market."),
    ),
  ),
  
  ),
  
  # REBAL SIMULATOR ####
  tabPanel(title=strong("Rebalancing Simulator"),
               fluidRow(align="center",
                    column(12,
                          h2("[COMING SOON]"),
                           ),
                    ),
  ),
  ),
  
  # Credits ####
  hr(),
  div(align="center",
      p("developed by:", a("C0dingM0nk3y", href="https://github.com/C0dingM0nk3y/"),
       ":|: source code available on GitHub:", a("investment-simulator", href="https://github.com/C0dingM0nk3y/investment-simulator"),
      ":|: Check out my repository for other tools for financial education", em("(coming soon)"))),
  hr(),
)
